name: PlatformIO CI

permissions:
  contents: write

on: [push, workflow_dispatch]

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/ui-ng/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Cache PIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            ~/.cache/pip
            ${{ github.workspace }}/.pio
          key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}

      - name: Setup Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Firmware Core
        run: | 
            pio run --disable-auto-clean -e esp32dev

      - name: Build Firmware LittleFS
        run: | 
            pio run --disable-auto-clean -e esp32dev -t buildfs

      - name: Build Full Firmware
        run: | 
            pio run --disable-auto-clean -e esp32dev -t merge_firmware

      - name: Prepare artifacts for archive 
        run: | 
            cp .pio/build/esp32dev/buildinfo.json buildinfo.json
            cp .pio/build/esp32dev/firmware_full.bin firmware_full.bin
            cp .pio/build/esp32dev/firmware.bin firmware.bin 
            cp .pio/build/esp32dev/firmware.elf firmware.elf
            cp .pio/build/esp32dev/littlefs.bin littlefs.bin
          
      - name: Archive Firmware Files
        uses: actions/upload-artifact@v4
        with: 
          name: firmware
          path: |
            buildinfo.json
            firmware.bin
            firmware_full.bin
            firmware.elf
            littlefs.bin

  build-flasher:
    needs: build-firmware
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Install required packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y libudev1 libudev-dev pkg-config

      - name: Cache Crates
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            ${{ github.workspace }}/rs-flasher/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust toolchain ${{ matrix.os }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Download Firmware Files
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: rs-flasher/resources

      - name: Build Flasher
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path rs-flasher/Cargo.toml

      - name: Copy result
        if: matrix.os == 'windows-latest'
        run: | 
            dir rs-flasher/target/release
            copy rs-flasher/target/release/rs-flasher.exe rs-flasher.exe

      - name: Copy result
        if: matrix.os == 'macos-latest'
        run: | 
            ls rs-flasher/target/release
            cp rs-flasher/target/release/rs-flasher rs-flasher.macOS

      - name: Copy result
        if: matrix.os == 'ubuntu-latest'
        run: | 
            ls rs-flasher/target/release
            cp rs-flasher/target/release/rs-flasher rs-flasher.linux-amd64

      - name: Archive Flasher
        uses: actions/upload-artifact@v4
        with: 
          name: flasher-${{matrix.os}}
          path: |
            rs-flasher.exe
            rs-flasher.macOS
            rs-flasher.linux-amd64

  release:
    needs: 
      - build-flasher
    if: startsWith(github.event.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: 
      name: github-releases
    steps:
    - name: Download Firmware Files
      id: download1
      uses: actions/download-artifact@v4
      with:
        name: firmware
    - name: Download Flasher Files
      id: download-mac
      uses: actions/download-artifact@v4
      with:
        pattern: flasher-*
        merge-multiple: true

    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4.1.1

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body: | 
          Files published:
           - rs-flasher - Tool to update firmware on your KNOMI without installing any dependencies
           - firmware_full.bin - Full image to be flashed by esptool 
           - firmware.bin - OTA update
           - firmware.elf - debug symbols
           - littlefs.bin - partition with resources

          ${{steps.build_changelog.outputs.changelog}}
        files: | 
          ${{steps.download1.outputs.download-path}}/firmware_full.bin
          ${{steps.download1.outputs.download-path}}/firmware.bin
          ${{steps.download1.outputs.download-path}}/firmware.elf
          ${{steps.download1.outputs.download-path}}/littlefs.bin
          ${{steps.download-win.outputs.download-path}}/rs-flasher.exe
          ${{steps.download-ubuntu.outputs.download-path}}/rs-flasher.linux-amd64
          ${{steps.download-mac.outputs.download-path}}/rs-flasher.macOS